/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DAO.HabitacionDAO;
import javax.swing.table.DefaultTableModel;
import modelo.Habitacion;
import modelo.TipoHabitacion;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class AppHabitacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppHabitacion.class.getName());

    /**
     * Creates new form AppHabitacion
     */
    public AppHabitacion() {
        initComponents();
        limpiarCampos();
        
        java.awt.EventQueue.invokeLater(() -> {
        AppCliente appCliente = new AppCliente();
        setJMenuBar(appCliente.crearBarra(480, 420, this));
        inicializarTabla();
        cargarDatos();
    });
    }
    
    DefaultTableModel modelo = new DefaultTableModel();
    HabitacionDAO dao = new HabitacionDAO();
    
    void inicializarTabla() {

    modelo.addColumn("ID");
    modelo.addColumn("Número");
    modelo.addColumn("Disponible");
    modelo.addColumn("Tipo Habitación");

    jTable4.setModel(modelo);
}
    
    void cargarDatos() {

    modelo.setRowCount(0);

    for(Habitacion h : dao.listar()) {

        modelo.addRow(new Object[]{

            h.getId_habitacion(),
            h.getNumero_habitacion(),
            h.isDisponible(),
            h.getTipoHabitacion().getNombre_tipo()

        });
    }
}
    
    void limpiarCampos() {

    txtNumeroHabitacion.setText("");
    chkDisponible.setSelected(false);
    txtTipoHab.setText("");
}
    
    void mostrarDatosFormulario() {

    int fila = jTable4.getSelectedRow();

    if(fila == -1) return;

    txtNumeroHabitacion.setText(
        jTable4.getValueAt(fila,1).toString()
    );

    chkDisponible.setSelected(
    Boolean.parseBoolean(
        jTable4.getValueAt(fila,2).toString()
    )
);

    txtTipoHab.setText(
        jTable4.getValueAt(fila,3).toString()
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroHabitacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTipoHab = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        chkDisponible = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Habitación"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Número de Habitación");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        jPanel1.add(txtNumeroHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 100, -1));

        jLabel4.setText("Tipo de Habitación");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, -1));
        jPanel1.add(txtTipoHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        chkDisponible.setText("Disponible");
        jPanel1.add(chkDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 380, 170));
        jPanel1.getAccessibleContext().setAccessibleName("Datos Habitacion"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla Habitación"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);
        jTable4.getAccessibleContext().setAccessibleParent(this);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 360, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 380, 250));
        jPanel2.getAccessibleContext().setAccessibleName("Tabla Habitacion");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {

        TipoHabitacion t = new TipoHabitacion();

        t.setId_tipo(
            Integer.parseInt(txtTipoHab.getText())
        );

        Habitacion h = new Habitacion(0,txtNumeroHabitacion.getText(),chkDisponible.isSelected(),t);

        dao.insertar(h);

        cargarDatos();
        limpiarCampos();
        
        JOptionPane.showMessageDialog(null,"Habitación registrada correctamente");

    } catch(Exception e) {

            e.printStackTrace();

            JOptionPane.showMessageDialog(
            null,
            e.getMessage()
    );
}
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = jTable4.getSelectedRow();

    if(fila == -1){

        javax.swing.JOptionPane.showMessageDialog(
            null,
            "Seleccione una habitación"
        );

        return;
    }

    try {

        int id = Integer.parseInt(
            jTable4.getValueAt(fila,0).toString()
        );

        TipoHabitacion t = new TipoHabitacion();

        t.setId_tipo(
            Integer.parseInt(txtTipoHab.getText())
        );

        Habitacion h = new Habitacion(
    id,
    txtNumeroHabitacion.getText(),
    chkDisponible.isSelected(),
    t
);

        dao.actualizar(h);

        cargarDatos();

        limpiarCampos();
        
        JOptionPane.showMessageDialog(null,"Habitación actualizada correctamente");

    } catch(Exception e) {

        e.printStackTrace();

            JOptionPane.showMessageDialog(
            null,
        e.getMessage()
    );
}
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = jTable4.getSelectedRow();

    if(fila == -1){

        javax.swing.JOptionPane.showMessageDialog(
            null,
            "Seleccione una habitación"
        );

        return;
    }

    try {

        int id = Integer.parseInt(
            jTable4.getValueAt(fila,0).toString()
        );

        dao.eliminar(id);

        cargarDatos();

        limpiarCampos();
        
        JOptionPane.showMessageDialog(null,"Habitación eliminada correctamente");

    } catch(Exception e) {

            e.printStackTrace();

            JOptionPane.showMessageDialog(
            null,
            e.getMessage()
    );
}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        mostrarDatosFormulario();
    }//GEN-LAST:event_jTable4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppHabitacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox chkDisponible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField txtNumeroHabitacion;
    private javax.swing.JTextField txtTipoHab;
    // End of variables declaration//GEN-END:variables
}
