/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DAO.ClientesDAO;
import DAO.HabitacionDAO;
import DAO.ReservaDAO;
import javax.swing.table.DefaultTableModel;
import modelo.Reserva;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import modelo.Cliente;
import modelo.Habitacion;
/**
 *
 * @author Usuario
 */
public class AppReserva extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppReserva.class.getName());

    /**
     * Creates new form AppReservas
     */
    public AppReserva() {
    initComponents();
    limpiarCampos();
    
    java.awt.EventQueue.invokeLater(() -> {
        AppCliente appCliente = new AppCliente();
        setJMenuBar(appCliente.crearBarra(480, 420, this));
        inicializarTabla();
        cargarDatos();
    });
}
    
    DefaultTableModel modelo = new DefaultTableModel();
    ReservaDAO dao = new ReservaDAO();
    ClientesDAO clientesDAO = new ClientesDAO();
    HabitacionDAO habitacionDAO = new HabitacionDAO();
    
    void mostrarDatosFormulario() {

    int fila = jTable1.getSelectedRow();

    if(fila == -1) return;

    lblFReserva.setText(
        jTable1.getValueAt(fila,1).toString()
    );

    txtFEntrada.setText(
        jTable1.getValueAt(fila,2).toString()
    );

    txtFSalida.setText(
        jTable1.getValueAt(fila,3).toString()
    );

    lblEstado.setText(
        jTable1.getValueAt(fila,4).toString()
    );

    txtCliente.setText(
        jTable1.getValueAt(fila,5).toString()
    );

    txtHabitacion.setText(
        jTable1.getValueAt(fila,6).toString()
    );
}

    void inicializarTabla() {
        
        modelo.addColumn("ID");
        modelo.addColumn("Fecha Reserva");
        modelo.addColumn("Fecha Entrada");
        modelo.addColumn("Fecha Salida");
        modelo.addColumn("Estado");
        modelo.addColumn("Cliente");
        modelo.addColumn("Habitación");

        
        jTable1.setModel(modelo);
}
    void cargarDatos() {
        modelo.setRowCount(0);
        for (Reserva r : dao.listar()) {

            modelo.addRow(new Object[]{
            r.getId_reserva(),
            r.getFecha_reserva(),
            r.getFecha_entrada(),
            r.getFecha_salida(),
            r.getEstado(),
            r.getCliente().getDocumento(),
            r.getHabitacion().getNumero_habitacion()
        });
    }
}
    void limpiarCampos() {
    txtCliente.setText("");
    txtFEntrada.setText("");
    txtFSalida.setText("");
    txtHabitacion.setText("");

    lblFReserva.setText("-");
    lblEstado.setText("Pendiente");

    jTable1.clearSelection();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFEntrada = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFSalida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblFReserva = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHabitacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Reserva"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("DNI Cliente");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 20));

        txtCliente.addActionListener(this::txtClienteActionPerformed);
        jPanel4.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, -1));

        jLabel8.setText("Fecha Entrada");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 20));
        jPanel4.add(txtFEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 130, -1));

        jLabel9.setText("Fecha Salida");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 20));
        jPanel4.add(txtFSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, -1));

        jLabel1.setText("Fecha Reserva");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        lblFReserva.setText("-");
        jPanel4.add(lblFReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 130, -1));

        jLabel3.setText("Numero Habitacion");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 120, 20));
        jPanel4.add(txtHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 120, -1));

        jLabel5.setText("Estado");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 50, -1));

        lblEstado.setText("-");
        jPanel4.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 120, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel4.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        jPanel4.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        jPanel4.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel4.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 250));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de Reservas"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 510, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 530, 250));

        getAccessibleContext().setAccessibleName("Reserva de Habitacion");
        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            mostrarDatosFormulario();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {

        SimpleDateFormat sdf =
                new SimpleDateFormat("yyyy-MM-dd");

        Cliente c = clientesDAO.buscarPorDocumento(
        txtCliente.getText());

if(c == null){

    JOptionPane.showMessageDialog(
            null,
            "Cliente no encontrado"
    );

    return;
}

Habitacion h = habitacionDAO.buscarPorNumero(
        txtHabitacion.getText()
);

if(h == null){

    JOptionPane.showMessageDialog(
            null,
            "Habitación no encontrada"
    );

    return;
}

        Reserva r = new Reserva(
                0,
                new Date(), // fecha reserva automática
                sdf.parse(txtFEntrada.getText()),
                sdf.parse(txtFSalida.getText()),
                "Pendiente",
                c,
                h
        );

        dao.insertar(r);

        cargarDatos();
        limpiarCampos();

        JOptionPane.showMessageDialog(
                null,
                "Reserva registrada correctamente"
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {

        int fila = jTable1.getSelectedRow();

        if(fila == -1){

            JOptionPane.showMessageDialog(
                null,
                "Seleccione una reserva"
            );

            return;
        }

        // VALIDACIÓN EXTRA
        if(lblFReserva.getText().equals("-")){

            JOptionPane.showMessageDialog(
                null,
                "Seleccione una reserva válida"
            );

            return;
        }

        int id = Integer.parseInt(
            jTable1.getValueAt(fila,0).toString()
        );

        SimpleDateFormat sdf =
                new SimpleDateFormat("yyyy-MM-dd");

        Cliente c = clientesDAO.buscarPorDocumento(
        txtCliente.getText()
);

if(c == null){

    JOptionPane.showMessageDialog(
            null,
            "Cliente no encontrado"
    );

    return;
}

Habitacion h = habitacionDAO.buscarPorNumero(
        txtHabitacion.getText()
);

if(h == null){

    JOptionPane.showMessageDialog(
            null,
            "Habitación no encontrada"
    );

    return;
}
Reserva r = new Reserva(
        id,
        sdf.parse(lblFReserva.getText()),
        sdf.parse(txtFEntrada.getText()),
        sdf.parse(txtFSalida.getText()),
        lblEstado.getText(),
        c,
        h
);

        dao.actualizar(r);

        cargarDatos();
        limpiarCampos();

        JOptionPane.showMessageDialog(
                null,
                "Reserva actualizada correctamente"
        );

    } catch(Exception e){

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    int fila = jTable1.getSelectedRow();

    if(fila == -1){

        JOptionPane.showMessageDialog(
            null,
            "Seleccione una reserva"
        );

        return;
    }

    int id = Integer.parseInt(
        jTable1.getValueAt(fila,0).toString()
    );

    dao.eliminar(id);

    cargarDatos();
    limpiarCampos();

    JOptionPane.showMessageDialog(
        null,
        "Reserva eliminada correctamente"
    );
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppReserva().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFReserva;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtFEntrada;
    private javax.swing.JTextField txtFSalida;
    private javax.swing.JTextField txtHabitacion;
    // End of variables declaration//GEN-END:variables
}
