/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DAO.ReservaDAO;
import javax.swing.table.DefaultTableModel;
import modelo.Reserva;
import java.text.SimpleDateFormat;
import modelo.Cliente;
import modelo.Habitacion;
/**
 *
 * @author Usuario
 */
public class AppReserva extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppReserva.class.getName());

    /**
     * Creates new form AppReservas
     */
    public AppReserva() { 
        initComponents();
        inicializarTabla();
        cargarDatos();
}
    
    DefaultTableModel modelo = new DefaultTableModel();
    ReservaDAO dao = new ReservaDAO();
    
    void mostrarDatosFormulario() {

    int fila = jTable1.getSelectedRow();

    if (fila == -1) return;

    txtFReserva.setText(
        jTable1.getValueAt(fila, 1).toString()
    );

    txtFEntrada.setText(
        jTable1.getValueAt(fila, 2).toString()
    );

    txtFSalida.setText(
        jTable1.getValueAt(fila, 3).toString()
    );

    txtEstado.setText(
        jTable1.getValueAt(fila, 4).toString()
    );

    txtCliente.setText(
        jTable1.getValueAt(fila, 5).toString()
    );

    txtHabitacion.setText(
        jTable1.getValueAt(fila, 6).toString()
    );
}

    void inicializarTabla() {
        
        modelo.addColumn("ID");
        modelo.addColumn("Fecha Reserva");
        modelo.addColumn("Fecha Entrada");
        modelo.addColumn("Fecha Salida");
        modelo.addColumn("Estado");
        modelo.addColumn("Cliente");
        modelo.addColumn("Habitación");

        
        jTable1.setModel(modelo);
}
    void cargarDatos() {
        modelo.setRowCount(0);
        for (Reserva r : dao.listar()) {

            modelo.addRow(new Object[]{
            r.getId_reserva(),
            r.getFecha_reserva(),
            r.getFecha_entrada(),
            r.getFecha_salida(),
            r.getEstado(),
            r.getCliente().getId_cliente(),
            r.getHabitacion().getId_habitacion()
        });
    }
}
    void limpiarCampos() {

    txtCliente.setText("");
    txtFReserva.setText("");
    txtFEntrada.setText("");
    txtFSalida.setText("");
    txtHabitacion.setText("");
    txtEstado.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtEstado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFReserva = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFEntrada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFSalida = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHabitacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 394, -1));

        jLabel6.setText("Cliente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 70, 20));

        txtCliente.addActionListener(this::txtClienteActionPerformed);
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 140, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        txtEstado.addActionListener(this::txtEstadoActionPerformed);
        jPanel2.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 140, -1));

        jLabel1.setText("Fecha Reserva");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 100, -1));
        jPanel2.add(txtFReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 140, -1));

        jLabel3.setText("Fecha Entrada");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, -1));
        jPanel2.add(txtFEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, -1));

        jLabel5.setText("Fecha Salida");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 100, -1));
        jPanel2.add(txtFSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 140, -1));

        jLabel7.setText("Habitación");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, -1));
        jPanel2.add(txtHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 140, -1));

        jLabel2.setText("Estado");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 60, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 700, 300));
        jPanel2.getAccessibleContext().setAccessibleName("Reserva de Habitacion");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 700, 230));

        getAccessibleContext().setAccessibleName("Reserva de Habitacion");
        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {

        java.util.Date fechaReserva =
            new SimpleDateFormat("yyyy-MM-dd")
            .parse(txtFReserva.getText());

        java.util.Date fechaEntrada =
            new SimpleDateFormat("yyyy-MM-dd")
            .parse(txtFEntrada.getText());

        java.util.Date fechaSalida =
            new SimpleDateFormat("yyyy-MM-dd")
            .parse(txtFSalida.getText());

        Cliente c = new Cliente();
        c.setId_cliente(Integer.parseInt(txtCliente.getText()));

        Habitacion h = new Habitacion();
        h.setId_habitacion(Integer.parseInt(txtHabitacion.getText()));

        Reserva r = new Reserva(
            0,
            fechaReserva,
            fechaEntrada,
            fechaSalida,
            txtEstado.getText(),
            c,
            h
        );

        dao.insertar(r);

        cargarDatos();

        limpiarCampos();

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
            null,
            "Error al guardar"
        );
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = jTable1.getSelectedRow();

    if (fila == -1) {

        javax.swing.JOptionPane.showMessageDialog(
            null,
            "Selecciona una reserva"
        );

        return;
    }

    try {

        int id = Integer.parseInt(
            jTable1.getValueAt(fila, 0).toString()
        );

        java.util.Date fechaReserva =
            new SimpleDateFormat("yyyy-MM-dd")
            .parse(txtFReserva.getText());

        java.util.Date fechaEntrada =
            new SimpleDateFormat("yyyy-MM-dd")
            .parse(txtFEntrada.getText());

        java.util.Date fechaSalida =
            new SimpleDateFormat("yyyy-MM-dd")
            .parse(txtFSalida.getText());

        Cliente c = new Cliente();
        c.setId_cliente(
            Integer.parseInt(txtCliente.getText())
        );

        Habitacion h = new Habitacion();
        h.setId_habitacion(
            Integer.parseInt(txtHabitacion.getText())
        );

        Reserva r = new Reserva(
            id,
            fechaReserva,
            fechaEntrada,
            fechaSalida,
            txtEstado.getText(),
            c,
            h
        );

        dao.actualizar(r);

        cargarDatos();

        limpiarCampos();

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
            null,
            "Error al actualizar"
        );
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = jTable1.getSelectedRow();

    if (fila == -1) {

        javax.swing.JOptionPane.showMessageDialog(
            null,
            "Selecciona una reserva"
        );

        return;
    }

    try {

        int id = Integer.parseInt(
            jTable1.getValueAt(fila, 0).toString()
        );

        dao.eliminar(id);

        cargarDatos();

        limpiarCampos();

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
            null,
            "Error al eliminar"
        );
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
            limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        mostrarDatosFormulario();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppReserva().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFEntrada;
    private javax.swing.JTextField txtFReserva;
    private javax.swing.JTextField txtFSalida;
    private javax.swing.JTextField txtHabitacion;
    // End of variables declaration//GEN-END:variables
}
