/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DAO.TipoHabitacionDAO;
import javax.swing.table.DefaultTableModel;
import modelo.TipoHabitacion;

public class AppTipoHabitacion extends javax.swing.JFrame {

    public AppTipoHabitacion() {
    initComponents();
    
    java.awt.EventQueue.invokeLater(() -> {
        AppCliente appCliente = new AppCliente();
        setJMenuBar(appCliente.crearBarra(480, 420, this));
        inicializarTabla();
        cargarDatos();
    });
}
    
    DefaultTableModel modelo = new DefaultTableModel();
    TipoHabitacionDAO dao = new TipoHabitacionDAO();
    
    void inicializarTabla() {

    modelo.addColumn("ID");
    modelo.addColumn("Nombre");
    modelo.addColumn("Precio");
    modelo.addColumn("Capacidad");

    Tabla.setModel(modelo);
}
    
    void cargarDatos() {

    modelo.setRowCount(0); // limpia la tabla

    for (TipoHabitacion t : dao.listar()) {

        modelo.addRow(new Object[]{
            t.getId_tipo(),
            t.getNombre_tipo(),
            t.getPrecio_noche(),
            t.getCapacidad()
        });
    }
}
    
    void mostrarDatosFormulario() {

    int fila = Tabla.getSelectedRow();

    if (fila == -1) return;

    txtNombre.setText(Tabla.getValueAt(fila, 1).toString());
    txtPrecio.setText(Tabla.getValueAt(fila, 2).toString());
    txtCapacidad.setText(Tabla.getValueAt(fila, 3).toString());
}
    
    void limpiarCampos() {
    txtNombre.setText("");
    txtPrecio.setText("");
    txtCapacidad.setText("");
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tipo de Habitacion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 16, 130, -1));

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, -1));

        jLabel2.setText("Precio por Noche");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 66, -1, -1));

        txtPrecio.addActionListener(this::txtPrecioActionPerformed);
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 66, 130, -1));

        jLabel3.setText("Capacidad de Personas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 112, -1, -1));

        txtCapacidad.addActionListener(this::txtCapacidadActionPerformed);
        getContentPane().add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 112, 130, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 168, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 168, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 168, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 168, -1, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 197, 470, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = Tabla.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(null, "Selecciona un registro");
        return;
    }

    try {

        int id = Integer.parseInt(Tabla.getValueAt(fila, 0).toString());

        dao.eliminar(id);

        cargarDatos();   // refresca tabla
        limpiarCampos(); // lo haremos después

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error al eliminar");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       try {

        TipoHabitacion t = new TipoHabitacion(
            0,
            txtNombre.getText(),
            Double.parseDouble(txtPrecio.getText()),
            Integer.parseInt(txtCapacidad.getText())
        );

        dao.insertar(t);

        cargarDatos();   // refresca tabla
        limpiarCampos(); // limpia inputs

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error al guardar");
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       int fila = Tabla.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(null, "Selecciona un registro");
        return;
    }

    try {

        int id = Integer.parseInt(Tabla.getValueAt(fila, 0).toString());

        TipoHabitacion t = new TipoHabitacion(
            id,
            txtNombre.getText(),
            Double.parseDouble(txtPrecio.getText()),
            Integer.parseInt(txtCapacidad.getText())
        );

        dao.actualizar(t);

        cargarDatos();   // refresca tabla
        limpiarCampos(); // (lo haremos después)

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error al actualizar");
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        mostrarDatosFormulario();
    }//GEN-LAST:event_TablaMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppTipoHabitacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private java.awt.Choice choice1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

}
